
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Omayr
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AdminDshbrdLogout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        AdminDshbrdStudentsBtn = new javax.swing.JLabel();
        AdminDshbrdTeachersBtn = new javax.swing.JLabel();
        AdminDshbrdModulesBtn = new javax.swing.JLabel();
        AdminDshbrdAssessmentsBtn = new javax.swing.JLabel();
        AdminDshbrdPaymentsBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Dashboard");

        AdminDshbrdLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        AdminDshbrdLogout.setText("Logout");
        AdminDshbrdLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminDshbrdLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(AdminDshbrdLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdminDshbrdLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(42, 42, 42))
        );

        AdminDshbrdStudentsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminDshbrdStudentsBtn.setText("Students");
        AdminDshbrdStudentsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDshbrdStudentsBtnMouseClicked(evt);
            }
        });

        AdminDshbrdTeachersBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminDshbrdTeachersBtn.setText("Teachers");
        AdminDshbrdTeachersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDshbrdTeachersBtnMouseClicked(evt);
            }
        });

        AdminDshbrdModulesBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminDshbrdModulesBtn.setText("Modules");
        AdminDshbrdModulesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDshbrdModulesBtnMouseClicked(evt);
            }
        });

        AdminDshbrdAssessmentsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminDshbrdAssessmentsBtn.setText("Assessments");
        AdminDshbrdAssessmentsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDshbrdAssessmentsBtnMouseClicked(evt);
            }
        });

        AdminDshbrdPaymentsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AdminDshbrdPaymentsBtn.setText("Payments");
        AdminDshbrdPaymentsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminDshbrdPaymentsBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AdminDshbrdStudentsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDshbrdTeachersBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDshbrdModulesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDshbrdAssessmentsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminDshbrdPaymentsBtn)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminDshbrdStudentsBtn)
                    .addComponent(AdminDshbrdTeachersBtn)
                    .addComponent(AdminDshbrdModulesBtn)
                    .addComponent(AdminDshbrdAssessmentsBtn)
                    .addComponent(AdminDshbrdPaymentsBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminDshbrdLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminDshbrdLogoutActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_AdminDshbrdLogoutActionPerformed

    private void AdminDshbrdStudentsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDshbrdStudentsBtnMouseClicked
        AdminManageStudent studentForm = new AdminManageStudent();
        studentForm.setLocationRelativeTo(this);
        studentForm.setVisible(true);
    }//GEN-LAST:event_AdminDshbrdStudentsBtnMouseClicked

    private void AdminDshbrdTeachersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDshbrdTeachersBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminDshbrdTeachersBtnMouseClicked

    private void AdminDshbrdModulesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDshbrdModulesBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminDshbrdModulesBtnMouseClicked

    private void AdminDshbrdAssessmentsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDshbrdAssessmentsBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminDshbrdAssessmentsBtnMouseClicked

    private void AdminDshbrdPaymentsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminDshbrdPaymentsBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminDshbrdPaymentsBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminDshbrdAssessmentsBtn;
    private javax.swing.JButton AdminDshbrdLogout;
    private javax.swing.JLabel AdminDshbrdModulesBtn;
    private javax.swing.JLabel AdminDshbrdPaymentsBtn;
    private javax.swing.JLabel AdminDshbrdStudentsBtn;
    private javax.swing.JLabel AdminDshbrdTeachersBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
